### ISSUE TITLE
Error on making `MyOs.bin`

### ISSUE THREAD

**Issue by rahatzamancse** [pritamzope/OS#2]
According to the `run.sh` file in `kernel_1` folder,  when running this command:
`gcc -T linker.ld -o MyOS.bin -ffreestanding -O2 -nostdlib kernel.o boot.o -lgcc`
I get the following error:
`/usr/bin/ld: boot.o: relocation R_X86_64_32 against '.multiboot' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status`

**Comment by Hampusm** [comment]
Me too. Please fix @pritamzope

**Comment by pritamzope** [comment]
It's because the kernel is for 32 bit(i386) not for 64 bit. so the size of multiboot header is different on different architectures.so compile and links the kernel as 32 bit(i386) options.also we are using gcc for linking, use ld for linking.
Here's the modified script contents.(Tested on Ubuntu_x86_64):

#assemble boot.s file
as --32 boot.s -o boot.o

#compile kernel.c file
gcc -m32 -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra

#linking the kernel with kernel.o and boot.o files
ld -m elf_i386 -T linker.ld kernel.o boot.o -o MyOS.bin -nostdlib

#check MyOS.bin file is x86 multiboot file or not
grub-file --is-x86-multiboot MyOS.bin

#building the iso file
mkdir -p isodir/boot/grub
cp MyOS.bin isodir/boot/MyOS.bin
cp grub.cfg isodir/boot/grub/grub.cfg
grub-mkrescue -o MyOS.iso isodir

#run it in qemu
qemu-system-x86_64 -cdrom MyOS.iso

**Comment by Hampusm** [comment]
@pritamzope 
```
[root@HampusPC HampOS]# bash run.sh
grub-mkrescue: error: `mformat` invocation failed
.
qemu-system-x86_64: -cdrom MyOS.iso: Could not open 'MyOS.iso': No such file or directory
```
